apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config
  ports:
    - port: {{ .Values.microservices.config.port }}
      targetPort: {{ .Values.microservices.config.port }}
  type: ClusterIP