apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
        - name: config
          image: { .Values.microservices.config.image }
          ports:
            - containerPort: { .Values.microservices.config.port }
---
apiVersion: v1
kind: Service
metadata:
  name: config
spec:
  selector:
    app: config
  ports:
    - port: { .Values.microservices.config.port }
      targetPort: { .Values.microservices.config.port }
  type: ClusterIP
