apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      initContainers:
        - name: wait-for-config
          image: busybox
          command: ['sh', '-c', 'until wget -qO- http://config-server:8888/actuator/health | grep UP; do echo waiting for config-server; sleep 5; done']
          # Timeout de 30 segundos por ejemplo
          terminationMessagePolicy: FallbackToLogsOnError
      containers:
        - name: eureka
          image: "{{ .Values.microservices.eureka.image }}"
          ports:
            - containerPort: {{ .Values.microservices.eureka.port }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.microservices.eureka.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  selector:
    app: eureka
  ports:
    - port: {{ .Values.microservices.eureka.port }}
      targetPort: {{ .Values.microservices.eureka.port }}
  type: ClusterIP
