apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      initContainers:
        - name: wait-for-config
          image: busybox
          command: ['sh', '-c', 'until wget -qO- http://config-server:8888/actuator/health | grep UP; do echo waiting for config-server; sleep 5; done']
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres {{ .Values.postgres.port }}; do echo waiting for postgres; sleep 5; done']
      containers:
        - name: inventory
          image: "{{ .Values.microservices.inventory.image }}"
          ports:
            - containerPort: {{ .Values.microservices.inventory.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: inventory
spec:
  selector:
    app: inventory
  ports:
    - port: {{ .Values.microservices.inventory.port }}
      targetPort: {{ .Values.microservices.inventory.port }}
  type: ClusterIP
