apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/BrunoC21/SGA_Gestion_Proyecto_Software.git
    targetRevision: HEAD
    path: charts/config-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true