microservices:
  eureka:
    image: brunocaro/microservice-eureka:7f11d28
    port: 8761
  gateway:
    image: brunocaro/microservice-gateway:7f11d28
    port: 8080

postgres:
  image: postgres:16
  port: 5432
  username: postgres
  password: postgres
  db: inventorydb

authPostgres:
  image: postgres:16
  port: 5432   # Puedes usar 5433 para evitar conflicto con el otro postgres
  username: postgres
  password: postgres
  db: authenticationdb
