server:
  port: 8761

spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    hostname: msvc-eureka
  client:
    register-with-eureka: true
    fetch-registry: false
    server-url:
      defaultZone: http://msvc-eureka:8761/eureka/