apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: "{{ .Values.microservices.authentication.image }}"
          ports:
            - containerPort: {{ .Values.microservices.authentication.port }}
          env:
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://config-server:8888/
---
apiVersion: v1
kind: Service
metadata:
  name: msvc-authentication
spec:
  selector:
    app: authentication
  ports:
    - port: {{ .Values.microservices.authentication.port }}
      targetPort: {{ .Values.microservices.authentication.port }}
  type: ClusterIP